---
on:
  push:

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # PACKER_LOG: 1

jobs:
  x86_64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          # - rockylinux-9
          - ubuntu-24.04
        provider:
          - virtualbox-iso
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Vagrant VirtualBox
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor | sudo tee /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          echo "deb [signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt-get update
          sudo apt-get install -y software-properties-common vagrant virtualbox-7.1
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Packer build
        run: |
          cd templates
          packer init .
          packer build -var-file="../os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-x86_64.pkrvars.hcl" .
      - name: Upload build artifact
        uses: actions/upload-artifact@main
        with:
          name: "${{ matrix.os }}-virtualbox-x86_64"
          path: |
            builds/*.box
            builds/*.json
          retention-days: 10
          compression-level: 0 # no compression
      - name: Bento Test
        run: |
          eval "$(chef shell-init bash)"
          export LOGNAME=$USER
          bento test
